"""change mail to email in users.model

Revision ID: f37f25b8ad67
Revises: eccbb4372971
Create Date: 2026-06-07 08:40:32.466697

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f37f25b8ad67"
down_revision: Union[str, None] = "eccbb4372971"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(length=100), nullable=False))
    op.drop_column("users", "mail")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("mail", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "email")
    # ### end Alembic commands ###
