"""del not null in phone email name in model user

Revision ID: ecd22836c78b
Revises: f37f25b8ad67
Create Date: 2026-06-08 09:48:52.483679

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ecd22836c78b"
down_revision: Union[str, None] = "f37f25b8ad67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "name", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column(
        "users", "phone", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "phone", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
